# Generated by Django 3.2 on 2021-04-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='img',
            field=models.ImageField(blank=True, default='aliment.jpg', upload_to=''),
        ),
    ]
