# Generated by Django 3.2 on 2021-05-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='voyage.jpg', upload_to='')),
                ('description', models.TextField(default='Non definie')),
            ],
        ),
    ]
