# Generated by Django 3.2 on 2021-05-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='voyage.jpg', upload_to='')),
                ('description', models.TextField(default='Non definie')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='adresse',
        ),
        migrations.AddField(
            model_name='contact',
            name='Avis',
            field=models.CharField(default='Non definie', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(default='Non definie', max_length=100),
        ),
    ]
