# Generated by Django 3.2 on 2021-05-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_plage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='voyage.jpg', upload_to='')),
                ('description', models.TextField(default='Non definie')),
            ],
        ),
    ]
